# Generated by Django 5.0 on 2023-12-26 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='completed_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
