# Generated by Django 5.0 on 2023-12-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_completed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
